//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddrTrie
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreetIndex
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string NameZh { get; set; }
        public Nullable<int> MainRoad { get; set; }
        public string Source { get; set; }
    }
}
